#SPDX-License-Identifier: GPL-3.0-only
---
namespace: bcduggan
name: qubes
version: 0.0.0
description: Opinionated Qubes workstation configuration
readme: README.md
authors:
  - "Brian Duggan <brian@dugga.net>"
license_file: LICENSE
tags:
  - qubes
  - workstation
#dependencies: {}
repository: "https://github.com/bcduggan/bcduggan.qubes"
#documentation: http://docs.example.com
#homepage: http://example.com
issues: https://github.com/bcduggan/bcduggan.qubes/issues
build_ignore:
  - .gitignore
  - .env.sh
  - mise.toml
  - cliff.toml
  - build/*
  - build
